### ISSUE TITLE
Exercise 6.8 (Variablen)

### ISSUE THREAD

**Issue by blackjackcola** [kandolfp/MECH-M-DUAL-1-SWD#13]
Is it on purpose that x is first described as prey population but is then a parameter of the predator class and vice versa with y ? 

<img width="731" alt="Bildschirmfoto 2024-11-24 um 18 33 52" src="https://github.com/user-attachments/assets/888e2a41-0763-40d3-b680-9f9b41b491b0">

**Comment by kandolfp** [comment]
Thanks, there is a typo here regarding the parameters $\alpha, \beta$ and $\delta, gamma$, they are switched. in the last two lines. 

Regarding the question:
Yes, it is a so called coupled system of differential equations. 
The growth of the population of prey depends on the population of the predator.

Regarding the implementation. For computing the next iteration of $x_k$, lets say $x_{k+1}$ the prey class technically only needs the current predators $y_k$ and not the parameters $\gamma, \delta$. So they can be private to the predator class as the prey does not need to see them and the same is true vice versa. On the other hand the population $x_k$ or $y_k$ needs to be available outside as they are parameters for the iteration.
