### ISSUE TITLE
Exercise 6.8 (Predator Prey simulation) The Lotka-Volterra Equations

### ISSUE THREAD

**Issue by TonyMCI** [kandolfp/MECH-M-DUAL-1-SWD#15]
According to StudySmarter, the definitions for the parameters in the Lotka-Volterra model are:

δ: growth rate of predators per consumed prey.
γ: Natural death rate of predators.

In the provided exercise, these definitions are swapped:

δ: Natural death rate of predators.
γ: growth rate of predators per consumed prey.

After swapping the values of δ and γ in my code, the model produced oscillatory behavior with the given parameter values, as expected.

Plot:
![Lotka-Volterra-Regel](https://github.com/user-attachments/assets/e26aacf9-5214-4bd1-badf-249a603103fb)

**Comment by TonyMCI** [comment]
sorry! wrong picture.
![Plot](https://github.com/user-attachments/assets/6515f11b-4624-4869-a6f8-6cda69df3aa8)

**Comment by kandolfp** [comment]
Thanks for checking this so thoroughly
