### ISSUE TITLE
fix: coloured text not displayed correctly

### ISSUE THREAD

**Issue by ziselsberger** [kandolfp/MECH-M-DUAL-1-SWD#2]
https://github.com/kandolfp/MECH-M-DUAL-1-SWD/blob/ac0d495d8cf15ef31dcb9589eb6a50eeeca3a95a/basics/versioncontrol.qmd#L136

https://github.com/kandolfp/MECH-M-DUAL-1-SWD/blob/ac0d495d8cf15ef31dcb9589eb6a50eeeca3a95a/basics/versioncontrol.qmd#L137

https://github.com/kandolfp/MECH-M-DUAL-1-SWD/blob/ac0d495d8cf15ef31dcb9589eb6a50eeeca3a95a/basics/versioncontrol.qmd#L184

**Comment by kandolfp** [comment]
Done
