### ISSUE TITLE
exercise5-9 Fehlender Eintrag im Dictionary ?

### ISSUE THREAD

**Issue by tobok-dot** [kandolfp/MECH-M-DUAL-1-SWD#5]
Fehlt im Dictionary der Eintrag "D"?
https://en.wikipedia.org/wiki/Roman_numerals

Sonst ist die Beispielzahl "MMMDCCXXIV" mit dem gegebenen Dictionary doch nicht lösbar?! "D", "MD" oder "DC" sind ja nicht im Dictionary vorhanden.

**Comment by kandolfp** [comment]
Thanks
