### ISSUE TITLE
Exercise5.10 - flat list of tuples - python interpreter simplifies tuple

### ISSUE THREAD

**Issue by tobok-dot** [kandolfp/MECH-M-DUAL-1-SWD#7]
Mit der gegeben Liste von tuples bekomme ich einen Fehler.
Die Liste wird beim testen vereinfacht, wodurch die Liste aus Tuples und Integern besteht. -> Screenshots
![grafik](https://github.com/user-attachments/assets/4751f487-867f-462a-9e35-1b4d2de79b0c)
![grafik](https://github.com/user-attachments/assets/b260f401-b7d3-4617-b440-848dc7e60bc4)

Lösung/Verbesserung?
Mit einem zusätzlichen Komma besteht die Liste komplett aus tuples, wodurch man über alle Elemente der Liste erneut iterieren kann:
![grafik](https://github.com/user-attachments/assets/64e6f1f9-f7e9-43bc-ae6d-aecd47c41628)

**Comment by kandolfp** [comment]
Danke fürs den Hinweis! 

Ich habe die Aufgabe in mehrere Schritte zerlegt damit besser verständlich ist was hier passiert. In der kurzen Form war das sicherlich nicht klar. 

Ist es so besser bzw. hat man einen _Lernerfolg_ -> `( )` kann von Python auf verschiedene Arten verwendet werden.
