### ISSUE TITLE
Exercise 5.11 und Exercise 5.12

### ISSUE THREAD

**Issue by tobok-dot** [kandolfp/MECH-M-DUAL-1-SWD#8]
Ich bin verwirrt bei Aufgabe 5.11 und 5.12.
Man soll in Aufgabe 5.11 ein Modul erstellen und in Aufgabe 5.12 das Modul mit pdm einbinden.

Wie ist das genau gedacht?
Zurzeit habe ich eine Project wo ich alle Aufgaben löse. Und wenn ich in dem Project ein Modul erstell, dann muss ich das nicht extra mit pdm installieren/hinzufügen.

Ist dann Aufgabe 5.12 so gedacht, dass man ein "externes locales" Module hinzufügt? Also das Aufgabe 5.11 in einem extra Project bearbeitet wird?
D.h ein neues git-Repo nur für die Aufgabe 5.11.

Oder sollen wir eine Dependency für das eigene Project erstellen, da Aufgabe 5.11 und 5.12 im selben Project sind? (So als Übung, auch wenn das nicht sehr realistisch ist)

Dank im Voraus!

**Comment by kandolfp** [comment]
https://pdm-project.org/latest/usage/dependency/#local-dependencies

https://docs.python.org/3/tutorial/modules.html#

Es ist nicht so unüblich, dass in einem repo mehrere Module verwaltet werden. In Python kann ein Ordner zu einem Modul werden. Manchmal entwickeln sich diese Module in so einer Art, dass sie eigenständig werden und damit auch eigenständig verwaltet. z.B hat `pytorch` ein `torch` und ein `torchgen` Module (https://github.com/pytorch/pytorch/tree/main).

Das Ziel von _Aufgabe 5.12_ ist:
- dass das Module aus _Aufgabe 5.11_ von `pdm` verwaltet wird also in `pdm list` auftaucht
- im header von _Aufgabe 5.12_  das module direkt mit `import module_ex511 ` importiert wird und nicht `import mci_softwaredesign/exercise5_11/date-checker.py` oder `import ../exercise5_11/date-checker`

Um es ganz klar zu trennen (auch mit Ordner) kannst du das Module auch ins root Verzeichnis des repos kopieren. 
ich würde aber immer sagen, es sollte kein zweites repo nötig sein.
